[package]
name = "bookerics_importer"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.28.0"
scraper = "0.12.0"
structopt = "0.3.26"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
